services:
  apiserver:
    container_name: clip-apiserver
    image: clip/apiserver
    restart: unless-stopped
    env_file:
      - path: .env
        required: true
    build:
      context: .
      dockerfile: ./apiserver/Dockerfile
      network: host
    networks:
      - clip-network

  spa:
    container_name: clip-spa
    image: clip/spa
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./spa/Dockerfile
      network: host
    env_file:
      - path: .env
        required: true
    networks:
      - clip-network

  proxy:
    container_name: clip-proxy
    image: clip/proxy
    restart: unless-stopped
    build:
      context: ./proxy
      dockerfile: ./Dockerfile
      network: host
    networks:
      - clip-network
    ports:
      - "432:80"
    depends_on:
      - clip-spa
      - clip-apiserver

networks:
  clip-network:
    name: clip_clip-network
    external: true