services:
  apiserver:
    container_name: clip-apiserver-dev
    image: clip/apiserver:debug
    entrypoint: /bin/sh ./apiserver.sh
    command: dev
    working_dir: /apiserver
    build:
      context: ./apiserver
      target: apiserver-base
      network: host
    env_file:
      - path: .env
        required: true
    ports:
      - ${CLIP_APISERVER_PORT}:${CLIP_APISERVER_PORT}
      - 5678:5678
    volumes:
      - ./apiserver:/apiserver

  spa:
    container_name: clip-spa-dev
    image: clip/spa:debug
    entrypoint: /bin/sh ./spa.sh
    command: dev
    working_dir: /spa
    build:
      context: ./spa
      target: spa-base
      network: host
    env_file:
      - path: .env
        required: true
    ports:
      - 4200:4200
      - 9222:9222
    volumes:
      - ./spa:/spa

  agent:
    container_name: clip-agent-dev
    image: clip/agent:debug
    entrypoint: /bin/sh ./agent.sh
    command: dev
    working_dir: /agent
    build:
      context: ./agent
      target: agent-base
      network: host
    env_file:
      - path: .env
        required: true
    environment:
      - HOME=/agent/.sdk
    volumes:
      - ./agent:/agent

  pgadmin:
    image: dpage/pgadmin4
    container_name: clip-dev-pgadmin4
    ports:
      - 8888:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${POSTGRESQL_USER}@clip.dev
      PGADMIN_DEFAULT_PASSWORD: ${POSTGRESQL_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    entrypoint: /bin/sh -c "chmod 600 /pgpass; /entrypoint.sh;"
    user: root
    configs:
      - source: servers.json
        target: /pgadmin4/servers.json
      - source: pgpass
        target: /pgpass

configs:
  pgpass:
    content: ${POSTGRESQL_HOST}:${POSTGRESQL_PORT}:*:${POSTGRESQL_USER}:${POSTGRESQL_PASSWORD}
  servers.json:
    content: |
      {
        "Servers": {
          "1": {
            "Group": "Servers",
            "Name": "My Local Postgres 16.1",
            "Host": "${POSTGRESQL_HOST}",
            "Port": ${POSTGRESQL_PORT},
            "MaintenanceDB": "clip",
            "Username": "${POSTGRESQL_USER}",
            "PassFile": "/pgpass",
            "SSLMode": "prefer"
          }
        }
      }
