services:
  proxy:
    container_name: clip-proxy
    image: clip/proxy
    restart: unless-stopped
    build:
      context: ./proxy
      dockerfile: ./Dockerfile
    ports:
      - 432:80
    env_file:
      - path: .env
        required: true

  apiserver:
    container_name: clip-apiserver
    image: clip/apiserver
    restart: unless-stopped
    build:
      context: ./apiserver
    env_file:
      - path: .env
        required: true

  spa:
    container_name: clip-spa
    image: clip/spa
    restart: unless-stopped
    build:
      context: ./spa
    env_file:
      - path: .env
        required: true