services:
  apiserver:
    container_name: clip-apiserver-dev
    image: clip/apiserver:debug
    command: /bin/sh ./apiserver.sh dev
    working_dir: /apiserver
    build:
      context: ./apiserver
      target: apiserver-base
      network: host
    develop:
      watch:
        - action: rebuild
          path: ./apiserver/pyproject.toml
    env_file:
      - path: .env
        required: true
    volumes:
      - ./apiserver/.venv:/apiserver/.venv
      - ./apiserver/dist:/apiserver/dist
      - ./apiserver/clip_apiserver:/apiserver/clip_apiserver
    ports:
      - ${CLIP_APISERVER_PORT}:${CLIP_APISERVER_PORT}
      - 5678:5678

  spa:
    container_name: clip-spa-dev
    image: clip/spa:debug
    command: /bin/sh ./spa.sh dev
    working_dir: /spa
    build:
      context: ./spa
      target: spa-base
      network: host
    develop:
      watch:
        - action: rebuild
          path: ./spa/package.json
        - action: rebuild
          path: ./spa/angular.json
    env_file:
      - path: .env
        required: true
    ports:
      - 4200:4200
      - 9222:9222
    volumes:
      - ./spa/node_modules:/spa/node_modules
      - ./spa/src:/spa/src
      - ./spa/dist:/spa/dist

  pgadmin:
    image: dpage/pgadmin4
    container_name: clip-dev-pgadmin4
    ports:
      - 8888:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${POSTGRESQL_USER}@clip.dev
      PGADMIN_DEFAULT_PASSWORD: ${POSTGRESQL_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    entrypoint: /bin/sh -c "chmod 600 /pgpass; /entrypoint.sh;"
    user: root
    configs:
      - source: servers.json
        target: /pgadmin4/servers.json
      - source: pgpass
        target: /pgpass

configs:
  pgpass:
    content: ${POSTGRESQL_HOST}:${POSTGRESQL_PORT}:*:${POSTGRESQL_USER}:${POSTGRESQL_PASSWORD}
  servers.json:
    content: |
      {
        "Servers": {
          "1": {
            "Group": "Servers",
            "Name": "My Local Postgres 16.1",
            "Host": "${POSTGRESQL_HOST}",
            "Port": ${POSTGRESQL_PORT},
            "MaintenanceDB": "clip",
            "Username": "${POSTGRESQL_USER}",
            "PassFile": "/pgpass",
            "SSLMode": "prefer"
          }
        }
      }
