services:

  apiserver:
    container_name: clip-apiserver-dev
    image: clip/apiserver:debug
    command: /bin/sh ./apiserver.sh dev
    working_dir: /apiserver
    build:
      context: .
      dockerfile: ./apiserver/Dockerfile
      target: apiserver-base
      network: host
    develop:
      watch:
        - action: rebuild
          path: ./apiserver/pyproject.toml
    env_file:
      - path: .env
        required: true
    volumes:
      # - ./apiserver/.venv:/apiserver/.venv
      # - ./apiserver/clip_apiserver:/apiserver/clip_apiserver
      # - ./apiserver/dist:/apiserver/dist
      - ./apiserver:/apiserver
    ports:
      - 8000:8000
      - 5678:5678

  spa:
    container_name: clip-spa-dev
    image: clip/spa:debug
    command: /bin/sh ./spa.sh dev
    working_dir: /spa
    build:
      context: ./spa
      dockerfile: ./spa/Dockerfile
      target: spa-base
      network: host
    develop:
      watch:
        - action: rebuild
          path: ./spa/package.json
        - action: rebuild
          path: ./spa/angular.json
    env_file:
      - path: .env
        required: true
    ports:
      - 4200:4200
      - 9222:9222
    volumes:
      - ./spa/node_modules:/spa/node_modules
      - ./spa/src:/spa/src
      - ./spa/dist:/spa/dist