services:
  proxy:
    container_name: clip-proxy
    image: clip/proxy
    restart: unless-stopped
    build:
      context: ./proxy
      dockerfile: ./Dockerfile
      network: host
    ports:
      - 432:80

  apiserver:
    container_name: clip-apiserver
    image: clip/apiserver
    restart: unless-stopped
    build:
      context: ./apiserver
      network: host
    env_file:
      - path: .env
        required: true

  spa:
    container_name: clip-spa
    image: clip/spa
    restart: unless-stopped
    build:
      context: ./spa
      network: host
    env_file:
      - path: .env
        required: true