services:

  apiserver:
    container_name: clip-apiserver-dev
    image: clip/apiserver:debug
    command: /bin/sh ../scripts/dev.sh apiserver
    working_dir: /clip/apiserver
    build:
      context: .
      dockerfile: ./apiserver/Dockerfile
      target: apiserver-base
      network: host
    develop:
      watch:
        - action: sync
          path: ./scripts
          target: /clip/scripts
        - action: sync
          path: ./apiserver
          target: /clip/apiserver
          ignore:
            - node_modules/
        - action: rebuild
          path: ./apiserver/pyproject.toml
    env_file:
      - path: .env
        required: true
    volumes:
      - ./apiserver/.venv:/clip/apiserver/.venv
    ports:
      - "8000:8000"
      - "5678:5678"
    networks:
      - clip-network

  spa:
    container_name: clip-spa-dev
    image: clip/spa:debug
    command: /bin/sh ../scripts/dev.sh spa
    working_dir: /clip/spa
    build:
      context: .
      dockerfile: ./spa/Dockerfile
      target: spa-base
      network: host
    develop:
      watch:
        - action: rebuild
          path: ./spa/package.json
        - action: rebuild
          path: ./spa/angular.json
    env_file:
      - path: .env
        required: true
    ports:
      - "4200:4200"
      - "9222:9222"
    volumes:
      - ./spa:/clip/spa
    networks:
      - clip-network

networks:
  clip-network:
