version: '3'
services:

  apiserver:
    container_name: clip-apiserver-debug
    image: clip/apiserver-debug
    command: /bin/sh dev.sh apiserver
    build:
      context: .
      dockerfile: apiserver/Dockerfile
      target: dev
    ports:
      - "8000:8000"
    volumes:
      - ./apiserver:/clip/apiserver
      - ./scripts:/clip/scripts

  spa:
    container_name: clip-spa-debug
    image: clip/spa-debug
    command: /bin/sh dev.sh spa
    build:
      context: .
      dockerfile: spa/Dockerfile
      target: dev
    ports: 
      - "4200:4200"
    volumes:
      - ./spa:/clip/spa
      - ./scripts:/clip/scripts
