services:
  postgres:
    container_name: postgres
    image: postgres:15.5
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
    volumes:
      - /var/lib/postgresql/data
    networks:
      - clip-network

networks:
  clip-network-base:
    name: clip-network