version: '3'
services:
  spa:
    container_name: clip-spa-debug
    image: clip/spa-debug
    build:
      context: ./spa
      dockerfile: Dockerfile.dev
    ports: 
      - "4200:4200"
    volumes:
      - /app/node_modules
      - ./spa:/app
  apiserver:
    container_name: clip-apiserver-debug
    image: clip/apiserver-debug
    build:
      context: ./apiserver
      dockerfile: Dockerfile.dev
    ports: 
      - "5299:5299"
    volumes:
      - ./apiserver:/app