version: '3'
services:

  clip-apiserver:
    container_name: clip-apiserver
    image: parisius/clip-apiserver
    restart: unless-stopped
    environment:
      - CLIP_APISERVER_PORT=8000
      - CLIP_APISERVER_HOST=0.0.0.0
    build:
      context: .
      dockerfile: ./apiserver/Dockerfile
    networks:
      - clip-network
    ports:
      - "8000:8000"

  clip-spa:
    container_name: clip-spa
    image: parisius/clip-spa
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./spa/Dockerfile
    networks:
      - clip-network
    ports:
      - "432:80"
      #- "443:443"

networks:
  clip-network:
    name: clip-network