version: "3.8"

services:
  clip:
    container_name: clip_dbg
    build:
      context: ./
      dockerfile: Dockerfile
      target: clip-debug
    image: parisius/clip_dbg
    ports:
      - "5000:5000"
    volumes:
      - ./:/clip
