version: "3.8"

services:

  ws:
    container_name: clip-ws
    build:
      context: ./
      dockerfile: Dockerfile
      target: webserver
    ports:
      - "5000:5000"
    volumes:
      - ./:/clip

  