version: '3'
services:

  clip:
    container_name: clip
    image: parisius/clip
    restart: unless-stopped
    environment:
      - CLIP_APISERVER_PORT=80
      - CLIP_APISERVER_HOST=0.0.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
      target: clip-prod
    ports:
      - 432:80