version: '3'
services:

  clip-server:
    container_name: clip-server
    image: clip/server
    build:
      context: .
      dockerfile: Dockerfile
      target: apiserver
    ports: 
      - "5000:5000"

  clip-spa:
    container_name: clip-spa
    image: clip/spa
    build:
      context: .
      dockerfile: Dockerfile
      target: spa
    ports: 
      - "432:80"