version: '3'
services:

  clip-spa-debug:
    container_name: clip-spa-debug
    image: clip/spa-debug
    user: node
    build:
      context: ./spa
      dockerfile: Dockerfile
    ports: 
      - "4200:4200"
    volumes:
      - ./spa:/app
    command: npm run docker

  clip-apiserver-debug:
    container_name: clip-apiserver-debug
    image: clip/apiserver-debug
    build:
      context: ./apiserver
      dockerfile: Dockerfile
    ports:
      - "5299:5299"
    volumes:
      - ./apiserver:/app
    command: dotnet watch Clip.Server.csproj
