version: "3.8"

services:

  clip:
    container_name: clip
    build:
      context: ./
      dockerfile: Dockerfile
      target: build
    image: parisius/clip
    ports:
      - "5000:5000"
    volumes:
      - ./:/clip