apiVersion: v1
kind: Service
metadata:
  name: {{ include "clip.fullname" . }}-apiserver
  labels:
    {{- include "clip.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8008
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "clip.selectorLabels" . | nindent 4 }}-apiserver
    app.kubernetes.io/instance: clip-apiserver