[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "pyclip"
version = "0.0.1"
dependencies = [
    "distro >= 1.6.0",
    "psutil >= 5.9.1"
]

[project.scripts]
tests = "tests:start_all"