[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "clip-server"
version = "0.0.1"
dependencies = [
    "Flask <= 2.2.0"
]

[project.optional-dependencies]
locals = [
  'pyclip >= 0.0.1',
]

[project.scripts]
clip-server = "clip_server.__main__:main"