# syntax=docker/dockerfile:1

FROM phusion/baseimage:jammy-1.0.0

RUN apt-get update \
    && apt-get install -y \
        --no-install-recommends \
        python3.11 \
        nodejs \
        npm \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN python --version
RUN node --version

CMD ["/run.sh"]
