image:
  repository: ghcr.io
  # This sets the pull policy for images.
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "0.0.1"

replicaCount: 1

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hostname: clip.lab.parisius.dev
  tls:
    - secretName: ssl-wildcard-lab-parisius-dev
      hosts:
        - clip.lab.parisius.dev

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

serviceAccount:
  automount: true
  annotations: {}